### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by sunlianlong** [LeaderAndMaster/vue2-element#1]
![image](https://cloud.githubusercontent.com/assets/22101668/23687072/cc3191ce-03e7-11e7-85b3-09ef59768931.png)

**Comment by LeaderAndMaster** [comment]
感觉是依赖没装好，npm install了吗

**Comment by sunlianlong** [comment]
已经全部下载了，看错误应该是文件内代码问题，应该是header.vue，如果是npm的话会提示npm错误的

**Comment by sunlianlong** [comment]
今天又看了一下，上面截图已经提示了，没有细看，是header.vue的div标签不严谨，修改后虽然跑通了但是在console里还是报这个错，不知道是哪个页面。
